version: "4"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=${telegram_token}
      - user_ids=${user_ids}
      - group_ids=${group_ids}
       - PORT=${PORT}
   ports:
      - "80:80"
    restart: unless-stopped
